config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:edit, :update]
  resources :articles do
    resources :votes, only: [:create, :destroy]
  end
  resources :categories, only: [:index, :show, :destroy]

  get 'user/sign_in', to: 'sessions#sign_in'
  post 'user/sign_in', to: 'sessions#create'
  delete 'user/log_out', to: 'sessions#log_out'

  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :content, :image, :author_id, presence: true
  validates :title, length: { in: 6..200 }
  validates :content, length: { in: 6..5000 }

  has_and_belongs_to_many :categories
  belongs_to :author, class_name: 'User'
  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user
  has_one_attached :image, dependent: :destroy

  scope :recent, -> { order('created_at desc').first }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :priority, presence: true

  has_and_belongs_to_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, too_short: 'name is too short' }

  has_many :authored_articles, class_name: 'Article', foreign_key: 'author_id', dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :voted_articles, through: :votes, source: :article
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :user_id, uniqueness: { scope: :article_id }
  validates :user_id, :article_id, presence: true

  belongs_to :user
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  helper_method :current_user, :require_login

  def current_user
    User.find(session[:current_user]) if session[:user_id]
    User.find(session[:current_user])
  end

  def require_login
    return if session[:current_user]

    redirect_to user_sign_in_path, alert: 'You must be signed in to access this section'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper

  before_action :require_login, only: %i[create new]

  def new
    @article = Article.new
  end

  def create
    @article = current_user.authored_articles.build(article_params)
    if @article.save
      create_categories(params[:article][:categories], @article)
      redirect_to article_path(@article), notice: 'Article created succesfully'
    else
      flash[:form_errors] = @article.errors
      redirect_to new_article_path, alert: 'This article can\'t be created'
    end
  end

  def show
    @article = Article.find(params[:id])
    @categories = @article.categories.map(&:name).join(', ')
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @most_pop = Article.where('id = ?', Vote.maximum('article_id')).first || Article.order('created_at desc').first
    @categories = Category.all
  end

  def show
    @category = Category.select('id', 'name').find(params[:id])
    @articles = @category.articles.order(created_at: :desc)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def sign_in; end

  def create
    @user = User.find_by(name: session_params[:name])
    if @user
      session[:current_user] = @user.id
      redirect_to root_path, notice: 'Sign in successfully'
    else
      session[:current_user] = nil
      redirect_to new_user_path, alert: 'User doesn\'t exist'
    end
  end

  def log_out
    session[:current_user] = nil
    redirect_to root_path, alert: 'You Logged out.'
  end

  private

  def session_params
    params.require(:session).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  before_action :same_user?, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:current_user] = @user.id
      redirect_to @user, notice: 'Sucessful Sign Up'
    else
      redirect_to new_user_path, alert: 'User already exist'
    end
  end

  def show
    @user = User.find(params[:id])
    @my_articles = @user.authored_articles
    @voted_articles = @user.voted_articles
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = current_user.votes.new(article_id: params[:article_id])

    if @vote.save
      redirect_to request.referrer, notice: 'You voted this post.'
    else
      redirect_to request.referrer, alert: 'You cant vote this post.'
    end
  end

  def destroy
    vote = Vote.find_by(id: params[:id], user: current_user, article_id: params[:article_id])
    if vote
      vote.destroy
      redirect_to request.referrer, alert: 'You unvoted this post.'
    else
      redirect_to request.referrer, alert: 'You cant unvote a post without a vote.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_or_not
    if Article.exists?
      render partial: 'have_articles'
    else
      render partial: 'no_articles'
    end
  end

  def login_or_logout
    if session[:current_user].nil?
      render partial: 'shared/log_in'
    else
      render partial: 'shared/log_out'
    end
  end

  def user_signed_in?
    !session[:current_user].nil?
  end

  def notice_or_alert
    if flash[:notice]
      render partial: 'shared/notice'
    elsif flash[:alert]
      render partial: 'shared/alert'
    end
  end

  def vote_or_unvote(article)
    return unless user_sign_in?

    vote = Vote.find_by(article: article, user: current_user)
    if vote
      render partial: 'shared/unvote', locals: { unvote: vote, article: article }
    else
      render partial: 'shared/vote', locals: { vote: vote, article: article }
    end
  end

  def user_sign_in?
    session[:current_user]
  end

  def user_link
    return unless user_sign_in?

    render partial: 'shared/user'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def create_categories(categories, article)
    categories.each do |key, value|
      next if value.nil?

      category = if Category.exists?(value.to_i)
                   Category.find(value.to_i)
                 else
                   Category.create(id: value.to_i,
                                   name: key.to_s)
                 end
      article.categories << category
    end
  end

  def title_error
    return unless flash[:form_errors]

    flash[:form_errors]['title'].first if flash[:form_errors].include?('title')
  end

  def content_error
    return unless flash[:form_errors]

    flash[:form_errors]['content'].first if flash[:form_errors].include?('content')
  end

  def image_error
    return unless flash[:form_errors]

    flash[:form_errors]['image'].first if flash[:form_errors].include?('image')
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def same_user?
    return if session[:current_user].to_i == params[:id].to_i

    redirect_to root_path, alert: 'You can\'t access this page'
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/new.html.erb
<section class='create-article container d-flex flex-column align-items-center pt-4 pb-4'>
  <h1 class='text-center mb-3'>Create An Article!</h1>
  <div class="article-form wrapper w-50">
    <%= form_for @article do |f| %>
      <div class="form-group pb-3">
        <%= f.label :title, class: 'mb-1' %>
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>
        <span class='error text-danger'><%= title_error %> </span>
      </div>

      <div class="form-group pb-3">
        <%= f.label :content, class: 'mb-1' %>
        <%= f.text_area :content, class: 'form-control' %>
        <span class='error text-danger'><%= content_error %> </span>
      </div>

      <div class="form-group pb-3 d-flex flex-column">
        <%= f.label :image, class: 'mb-1' %>
        <%= f.file_field :image, direct_upload: true, class: 'form-control-file', accept: 'image/*' %>
        <span class='error text-danger'><%= image_error %> </span>
      </div>

      <%= f.fields_for :categories do |c| %>
        <%= c.label :name, 'Select categories', class: 'mb-1' %> <br>
        <div class="d-flex form-group justify-content-between mb-3">
          <div>
            <%= c.check_box 'Video Games', {} , 1 , nil%>
            <%= c.label 'Video Games' %>
          </div>
          <div>
            <%= c.check_box :Computers, {} , 2 , nil %>
            <%= c.label :Computers %>
          </div>
          <div>
            <%= c.check_box :Phones, {} , 3 , nil %>
            <%= c.label :Phones %>
          </div>
          <div>
            <%= c.check_box :Robotics, {} , 4 , nil %>
            <%= c.label :Robotics %>
          </div>
        </div>
      <% end %>

      <%= f.submit 'Create', class: 'btn btn-success w-100' %>
    <% end %>
  </div>
</section>

app/views/articles/show.html.erb
<div class="container articles pt-5 mb-5">
  <div class='title text-center mb-5 text-light-green'><%= @article.title %></div>
  <div class="article-image">
    <%= image_tag url_for(@article.image), class: 'w-100 mb-3' %>
  </div>
  <div class='info-group d-flex justify-content-between p-2 text-light-green'>
    <span class="time">
      Created on: 
      <%= @article.created_at.strftime("%m/%d/%Y") %>
    </span>
    <span class="category">
      Categories: 
      <span class='text-primary'>
        <%= @categories %>
      </span> 
    </span>
    <br>
    <span><%= vote_or_unvote(@article) %> | <%= @article.votes.count %> Votes</span>
  </div>
  <p class='content p-3'><%= @article.content %></p>
</div> 

app/views/categories/_article.html.erb
<article class='article-img'>
  <%= image_tag article.image %>
</article>

<article class='article-text p-3 d-flex flex-column'>
  <span class='category mb-3 pb-1'><%= @category.name %></span>
  <span class='title mb-3'><%= article.title %></span>
  <p content='content'><%= article.content.truncate(150) %></p>
  <span class='title mb-3'><span class="text-light-green">Author:</span> <%= article.author.name %></span>
  <span><%= vote_or_unvote(article) %><span class='text-darkblue'> | <%= article.votes.count %> Votes</span></span>
  <%= link_to 'Read more..', article_path(article) %>
</article> 

app/views/categories/_category.html.erb
<article class='cate col p-0'>
  <div class='wrapper w-100 d-flex flex-column position-relative justify-content-between'>
    <%= link_to category_path(category) do %>
      <div class='gradient'></div>
    <% end %>
    <%= link_to category_path(category) do %>
      <span class='category-name text-white'><%= category.name %></span>
    <% end %>
    <span class='article-title text-white'><%= link_to category.articles.recent.title, category.articles.recent %></span>
    <%= image_tag category.articles.recent.image %>
  </div>
</article>

app/views/categories/_have_articles.html.erb
<section class='most-pop'>
  <div class='wrapper w-100 d-flex flex-column position-relative justify-content-between'>
    <%= link_to article_path(@most_pop) do %>
      <div class='gradient'></div>
    <% end %>
      <span class='article-title text-white'><%= link_to @most_pop.title, article_path(@most_pop) %></span>
      <%= image_tag @most_pop.image %>
  </div>
</section>

<section class='categories'>
  <div class="row m-0">
    <%= render partial: 'category', collection: @categories %>
  </div>
</section> 

app/views/categories/_no_articles.html.erb
<section class="no-articles container d-flex justify-content-center align-items-center">
  <h2 class="text-light-orange text-center">There are no articles published at the moment<br> Please come back later. </h2>
</section> 

app/views/categories/index.html.erb
<%= show_or_not %>

app/views/categories/show.html.erb
<section class='art-x-cat'>
  <div class='d-flex flex-wrap'>      
    <%= render partial: 'article', collection: @articles %>
  </div>
</section> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechMagz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='max-w'>
    <header  class='border border-top-0'>
      <%= render 'shared/navbar' %>
    </header>
    <%= notice_or_alert %>

    <main  class='w-100'>
      <%= yield %>
    </main>

    <footer class='max-w'>
      <%= render 'shared/footer' %>
    </footer>
  </body>

</html>

app/views/shared/_alert.html.erb
<div class='alert alert-danger text-center position-absolute w-100 max-w'>
  <%= flash[:alert] %>
</div> 

app/views/shared/_footer.html.erb
<div class='footer d-flex bg-brown w-100 p-2 align-items-center justify-content-between'>
  <div class='logo text-white'>
    TechMagz
  </div>

  <div class='info'>
    <%= link_to 'Original Idea', 'https://www.behance.net/gallery/14554909/liFEsTlye-Mobile-version' %>
    <span class='ml-1 text-white'>Copyright 2014. All rights reserved.</span>
  </div>

  <div class="social-links">
    <span class='text-white'>Contact with me:</span>
    <%= link_to 'https://twitter.com/Alan55572391' do %>
      <svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><path d="m256 0c-141.363281 0-256 114.636719-256 256s114.636719 256 256 256 256-114.636719 256-256-114.636719-256-256-256zm116.886719 199.601562c.113281 2.519532.167969 5.050782.167969 7.59375 0 77.644532-59.101563 167.179688-167.183594 167.183594h.003906-.003906c-33.183594 0-64.0625-9.726562-90.066406-26.394531 4.597656.542969 9.277343.8125 14.015624.8125 27.53125 0 52.867188-9.390625 72.980469-25.152344-25.722656-.476562-47.410156-17.464843-54.894531-40.8125 3.582031.6875 7.265625 1.0625 11.042969 1.0625 5.363281 0 10.558593-.722656 15.496093-2.070312-26.886718-5.382813-47.140624-29.144531-47.140624-57.597657 0-.265624 0-.503906.007812-.75 7.917969 4.402344 16.972656 7.050782 26.613281 7.347657-15.777343-10.527344-26.148437-28.523438-26.148437-48.910157 0-10.765624 2.910156-20.851562 7.957031-29.535156 28.976563 35.554688 72.28125 58.9375 121.117187 61.394532-1.007812-4.304688-1.527343-8.789063-1.527343-13.398438 0-32.4375 26.316406-58.753906 58.765625-58.753906 16.902344 0 32.167968 7.144531 42.890625 18.566406 13.386719-2.640625 25.957031-7.53125 37.3125-14.261719-4.394531 13.714844-13.707031 25.222657-25.839844 32.5 11.886719-1.421875 23.214844-4.574219 33.742187-9.253906-7.863281 11.785156-17.835937 22.136719-29.308593 30.429687zm0 0"/></svg>
    <% end %>
    
    <%= link_to 'https://github.com/warblo001' do %>
      <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
        <g>
          <g>
            <path d="M255.968,5.329C114.624,5.329,0,120.401,0,262.353c0,113.536,73.344,209.856,175.104,243.872
              c12.8,2.368,17.472-5.568,17.472-12.384c0-6.112-0.224-22.272-0.352-43.712c-71.2,15.52-86.24-34.464-86.24-34.464
              c-11.616-29.696-28.416-37.6-28.416-37.6c-23.264-15.936,1.728-15.616,1.728-15.616c25.696,1.824,39.2,26.496,39.2,26.496
              c22.848,39.264,59.936,27.936,74.528,21.344c2.304-16.608,8.928-27.936,16.256-34.368
              c-56.832-6.496-116.608-28.544-116.608-127.008c0-28.064,9.984-51.008,26.368-68.992c-2.656-6.496-11.424-32.64,2.496-68
              c0,0,21.504-6.912,70.4,26.336c20.416-5.696,42.304-8.544,64.096-8.64c21.728,0.128,43.648,2.944,64.096,8.672
              c48.864-33.248,70.336-26.336,70.336-26.336c13.952,35.392,5.184,61.504,2.56,68c16.416,17.984,26.304,40.928,26.304,68.992
              c0,98.72-59.84,120.448-116.864,126.816c9.184,7.936,17.376,23.616,17.376,47.584c0,34.368-0.32,62.08-0.32,70.496
              c0,6.88,4.608,14.88,17.6,12.352C438.72,472.145,512,375.857,512,262.353C512,120.401,397.376,5.329,255.968,5.329z"/>
          </g>
        </g>
      </svg>
    <% end %>
      
    <%= link_to 'https://www.linkedin.com/in/alan-solis/' do %>
      <svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><path d="m256 0c-141.363281 0-256 114.636719-256 256s114.636719 256 256 256 256-114.636719 256-256-114.636719-256-256-256zm-74.390625 387h-62.347656v-187.574219h62.347656zm-31.171875-213.1875h-.40625c-20.921875 0-34.453125-14.402344-34.453125-32.402344 0-18.40625 13.945313-32.410156 35.273437-32.410156 21.328126 0 34.453126 14.003906 34.859376 32.410156 0 18-13.53125 32.402344-35.273438 32.402344zm255.984375 213.1875h-62.339844v-100.347656c0-25.21875-9.027343-42.417969-31.585937-42.417969-17.222656 0-27.480469 11.601563-31.988282 22.800781-1.648437 4.007813-2.050781 9.609375-2.050781 15.214844v104.75h-62.34375s.816407-169.976562 0-187.574219h62.34375v26.558594c8.285157-12.78125 23.109375-30.960937 56.1875-30.960937 41.019531 0 71.777344 26.808593 71.777344 84.421874zm0 0"/></svg>
    <% end %>
  </div>
</div>

app/views/shared/_log_in.html.erb
<%= link_to 'Sign In', user_sign_in_path %>| 
<%= link_to 'Sign Up', new_user_path %> 

app/views/shared/_log_out.html.erb
<%= link_to 'Log Out', user_log_out_path, method: 'Delete' %>

app/views/shared/_navbar.html.erb
<nav class='navbar bg-light p-2 h-100 border-bottom'>
  <%= link_to 'TechMagz', root_path, class: 'navbar-brand text-brown pl-3' %>
  <div class="nav-links">
    <%= link_to 'Home', root_path %>
    <%= link_to 'New Article', new_article_path %>
    <%= user_link %>
  </div>
  <div class="nav-links">
    <%= login_or_logout %>
  </div>
</nav>

app/views/shared/_notice.html.erb
<div class='alert alert-success text-center position-absolute w-100 max-w'>
  <%= flash[:notice] %>
</div> 

app/views/shared/_unvote.html.erb
<%= link_to 'Unvote!', article_vote_path(id: unvote.id, article_id: article.id), method: :delete, class: 'vote' %> 

app/views/shared/_user.html.erb
<% if current_user != nil %>
  <%= link_to current_user.name.capitalize, user_path(session[:current_user]) %>
<% else %>
  <%= link_to " ", user_sign_in_path, class: 'form-link' %>
<% end %>

app/views/shared/_vote.html.erb
<%= link_to 'Vote!', article_votes_path(article_id: article.id), method: :post, class: 'vote' %>

app/views/users/_article.html.erb
<li><%= link_to article.title, article_path(article) %></li> 

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-group mb-3">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit "Sign up", class: 'btn btn-success mb-2' %>
<% end %>

app/views/users/new.html.erb
<div class="signs d-flex align-items-center justify-content-center">
  <div class="user-forms container w-25 d-flex flex-column justify-content-center border p-5 rounded">
    <h1>Sign Up</h1>
    <%= render 'form' %>
    <span class='mt-2'>Have an account? <%= link_to "Sign in", user_sign_in_path, class: 'form-link' %></span>
  </div>
</div>

app/views/users/show.html.erb
<div class="user container d-flex flex-column justify-content-center align-items-center h-100 pt-5">
  <h1 class='pb-3'>Welcome <%= @user.name %></h1>
  <div>
    <h3>My articles</h3>
    <ul>
      <%= render partial: 'article', collection: @my_articles %>
    </ul>
    <h3>Voted articles</h3>
    <ul>
      <%= render partial: 'article', collection: @voted_articles %>
    </ul>
  </div>
</div>